using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AIAppForm
{
    internal class ListPTHH
    {
        private List<PTHH> R;
        private static ListPTHH instance;

        internal List<PTHH> LPTHH { get => R; set => R = value; }
        internal static ListPTHH Instance { 
            get
            {
                if (instance == null)
                    instance = new ListPTHH();
                return instance;
            }
               
            
            set => instance = value; }
        private ListPTHH()
        {
            R = new List<PTHH>();
            R.Add(new PTHH(new List<string> { "HCl", "K" }, "KCl"));
            R.Add(new PTHH(new List<string> { "HCl", "K" }, "H2"));
            R.Add(new PTHH(new List<string> { "HCl", "Na" }, "NaCl"));
            R.Add(new PTHH(new List<string> { "HCl", "Na" }, "H2"));
            R.Add(new PTHH(new List<string> { "HCl", "Ca" }, "CaCl2"));
            R.Add(new PTHH(new List<string> { "HCl", "Ca" }, "H2"));
            R.Add(new PTHH(new List<string> { "HCl", "Mg" }, "MgCl2"));
            R.Add(new PTHH(new List<string> { "HCl", "Mg" }, "H2"));
            R.Add(new PTHH(new List<string> { "HCl", "Al" }, "AlCl3"));
            R.Add(new PTHH(new List<string> { "HCl", "Al" }, "H2"));
            R.Add(new PTHH(new List<string> { "HCl", "Zn" }, "ZnCl2"));
            R.Add(new PTHH(new List<string> { "HCl", "Zn" }, "H2"));
            R.Add(new PTHH(new List<string> { "HCl", "Fe" }, "FeCl2"));
            R.Add(new PTHH(new List<string> { "HCl", "Fe" }, "H2"));
            R.Add(new PTHH(new List<string> { "HCl", "Cu" }, "CuCl2"));
            R.Add(new PTHH(new List<string> { "HCl", "Cu" }, "H2"));
            R.Add(new PTHH(new List<string> { "HCl", "MgO" }, "MgCl2"));
            R.Add(new PTHH(new List<string> { "HCl", "MgO" }, "H2O"));
            R.Add(new PTHH(new List<string> { "HCl", "Fe2O3" }, "FeCl3"));
            R.Add(new PTHH(new List<string> { "HCl", "Fe2O3" }, "H2O"));
            R.Add(new PTHH(new List<string> { "HCl", "NaOH" }, "NaCl"));
            R.Add(new PTHH(new List<string> { "HCl", "NaOH" }, "H2O"));
            R.Add(new PTHH(new List<string> { "HCl", "Na2CO3" }, "NaCl"));
            R.Add(new PTHH(new List<string> { "HCl", "Na2CO3" }, "H2O"));
            R.Add(new PTHH(new List<string> { "HCl", "Na2CO3" }, "CO2"));
            R.Add(new PTHH(new List<string> { "Zn", "O2" }, "ZnO"));
            R.Add(new PTHH(new List<string> { "Fe", "O2" }, "Fe2O3"));
            R.Add(new PTHH(new List<string> { "Al", "O2" }, "Al2O3"));
            R.Add(new PTHH(new List<string> { "Cu", "O2" }, "CuO"));
            R.Add(new PTHH(new List<string> { "Cr", "O2" }, "Cr2O3"));
            R.Add(new PTHH(new List<string> { "Al", "NaOH", "H2O" }, "NaAlO2"));
            R.Add(new PTHH(new List<string> { "Al", "NaOH", "H2O" }, "H2"));
            R.Add(new PTHH(new List<string> { "Al", "Ba(OH)2", "H2O" }, "Ba(AlO2)2"));
            R.Add(new PTHH(new List<string> { "Al", "Ba(OH)2", "H2O" }, "H2"));
            R.Add(new PTHH(new List<string> { "Al", "CuSO4" }, "Al2(SO4)3"));
            R.Add(new PTHH(new List<string> { "Al", "CuSO4" }, "Cu"));
            R.Add(new PTHH(new List<string> { "NaOH", "Al2O3" }, "NaAlO2"));
            R.Add(new PTHH(new List<string> { "NaOH", "Al2O3" }, "H2O"));
            R.Add(new PTHH(new List<string> { "NaOH", "SiO2" }, "Na2SiO3"));
            R.Add(new PTHH(new List<string> { "NaOH", "SiO2" }, "H2O"));
            R.Add(new PTHH(new List<string> { "NaAlO2", "CO2", "H2O" }, "NaHCO3"));
            R.Add(new PTHH(new List<string> { "NaAlO2", "CO2", "H2O" }, "Al(OH)3"));
            R.Add(new PTHH(new List<string> { "NaOH", "CO2" }, "NaHCO3"));
            R.Add(new PTHH(new List<string> { "Al(OH)3" }, "Al2O3"));
            R.Add(new PTHH(new List<string> { "Al(OH)3" }, "H2O"));
            R.Add(new PTHH(new List<string> { "Al2O3" }, "Al"));
            R.Add(new PTHH(new List<string> { "Al2O3" }, "O2"));
            R.Add(new PTHH(new List<string> { "Cr2O3", "Al" }, "Al2O3"));
            R.Add(new PTHH(new List<string> { "Cr2O3", "Al" }, "Cr"));
            R.Add(new PTHH(new List<string> { "AlCl3", "K" }, "Al"));
            R.Add(new PTHH(new List<string> { "AlCl3", "K" }, "KCl"));
            R.Add(new PTHH(new List<string> { "Al2(SO4)3", "Mg" }, "Al"));
            R.Add(new PTHH(new List<string> { "Al2(SO4)3", "Mg" }, "MgSO4"));
            R.Add(new PTHH(new List<string> { "AlCl3", "Mg" }, "Al"));
            R.Add(new PTHH(new List<string> { "AlCl3", "Mg" }, "MgCl2"));
            R.Add(new PTHH(new List<string> { "AlCl3" }, "Al"));
            R.Add(new PTHH(new List<string> { "AlCl3" }, "Cl2"));
            R.Add(new PTHH(new List<string> { "FeS" }, "Fe"));
            R.Add(new PTHH(new List<string> { "FeS" }, "S"));
            R.Add(new PTHH(new List<string> { "CO", "FeO" }, "Fe"));
            R.Add(new PTHH(new List<string> { "CO", "FeO" }, "CO2"));
            R.Add(new PTHH(new List<string> { "FeO" }, "Fe"));
            R.Add(new PTHH(new List<string> { "FeO" }, "Fe3O4"));
            R.Add(new PTHH(new List<string> { "Al", "FeCl3" }, "AlCl3"));
            R.Add(new PTHH(new List<string> { "Al", "FeCl3" }, "Fe"));
            R.Add(new PTHH(new List<string> { "C", "FeO" }, "CO"));
            R.Add(new PTHH(new List<string> { "C", "FeO" }, "Fe"));
            R.Add(new PTHH(new List<string> { "FeCl2", "Mg" }, "Fe"));
            R.Add(new PTHH(new List<string> { "FeCl2", "Mg" }, "MgCl2"));
            R.Add(new PTHH(new List<string> { "FeCl2" }, "Cl2"));
            R.Add(new PTHH(new List<string> { "FeCl2" }, "Fe"));
            R.Add(new PTHH(new List<string> { "CuSO4", "Fe" }, "Cu"));
            R.Add(new PTHH(new List<string> { "CuSO4", "Fe" }, "FeSO4"));
            R.Add(new PTHH(new List<string> { "CuSO4", "Zn" }, "Cu"));
            R.Add(new PTHH(new List<string> { "CuSO4", "Zn" }, "ZnSO4"));
            R.Add(new PTHH(new List<string> { "CuSO4", "Mg" }, "Cu"));
            R.Add(new PTHH(new List<string> { "CuSO4", "Mg" }, "MgSO4"));
            R.Add(new PTHH(new List<string> { "CuO", "CO" }, "Cu"));
            R.Add(new PTHH(new List<string> { "CuO", "CO" }, "CO2"));
            R.Add(new PTHH(new List<string> { "Cu(OH)2" }, "CuO"));
            R.Add(new PTHH(new List<string> { "Cu(OH)2" }, "H2O"));
            R.Add(new PTHH(new List<string> { "Cu(OH)2", "HCl" }, "CuCl2"));
            R.Add(new PTHH(new List<string> { "Cu(OH)2", "HCl" }, "H2O"));
            R.Add(new PTHH(new List<string> { "KI" }, "I2"));
            R.Add(new PTHH(new List<string> { "KI" }, "K"));
            R.Add(new PTHH(new List<string> { "KF" }, "F2"));
            R.Add(new PTHH(new List<string> { "KF" }, "K"));
            R.Add(new PTHH(new List<string> { "C", "K2CO3" }, "CO"));
            R.Add(new PTHH(new List<string> { "C", "K2CO3" }, "K"));
            R.Add(new PTHH(new List<string> { "KNH2" }, "K"));
            R.Add(new PTHH(new List<string> { "KNH2" }, "N2"));
            R.Add(new PTHH(new List<string> { "KNH2" }, "NH3"));
            R.Add(new PTHH(new List<string> { "K2O" }, "K"));
            R.Add(new PTHH(new List<string> { "K2O" }, "K2O2"));
            R.Add(new PTHH(new List<string> { "KCl" }, "Cl2"));
            R.Add(new PTHH(new List<string> { "KCl" }, "K"));
            R.Add(new PTHH(new List<string> { "CaC2", "KF" }, "C"));
            R.Add(new PTHH(new List<string> { "CaC2", "KF" }, "CaF2"));
            R.Add(new PTHH(new List<string> { "CaC2", "KF" }, "K"));
            R.Add(new PTHH(new List<string> { "H2", "K2O" }, "H2O"));
            R.Add(new PTHH(new List<string> { "H2", "K2O" }, "K"));
            R.Add(new PTHH(new List<string> { "C", "K2O" }, "K"));
            R.Add(new PTHH(new List<string> { "C", "K2O" }, "CO2"));
            R.Add(new PTHH(new List<string> { "K2O", "NH3" }, "H2O"));
            R.Add(new PTHH(new List<string> { "K2O", "NH3" }, "K"));
            R.Add(new PTHH(new List<string> { "K2O", "NH3" }, "N2"));
            R.Add(new PTHH(new List<string> { "Al", "K2O" }, "Al2O3"));
            R.Add(new PTHH(new List<string> { "Al", "K2O" }, "K"));
            R.Add(new PTHH(new List<string> { "NaCl" }, "Cl2"));
            R.Add(new PTHH(new List<string> { "NaCl" }, "Na"));
            R.Add(new PTHH(new List<string> { "NaOH" }, "H2O"));
            R.Add(new PTHH(new List<string> { "NaOH" }, "Na"));
            R.Add(new PTHH(new List<string> { "NaOH" }, "O2"));
            R.Add(new PTHH(new List<string> { "C", "Na2CO3" }, "CO"));
            R.Add(new PTHH(new List<string> { "C", "Na2CO3" }, "Na"));
            R.Add(new PTHH(new List<string> { "Na2O" }, "Na"));
            R.Add(new PTHH(new List<string> { "Na2O" }, "Na2O2"));
            R.Add(new PTHH(new List<string> { "NaI" }, "I2"));
            R.Add(new PTHH(new List<string> { "NaI" }, "Na"));
            R.Add(new PTHH(new List<string> { "NaH" }, "H2"));
            R.Add(new PTHH(new List<string> { "NaH" }, "Na"));
            R.Add(new PTHH(new List<string> { "NaN3" }, "N2"));
            R.Add(new PTHH(new List<string> { "NaN3" }, "Na"));
            R.Add(new PTHH(new List<string> { "NaNH2" }, "N2"));
            R.Add(new PTHH(new List<string> { "NaNH2" }, "Na"));
            R.Add(new PTHH(new List<string> { "NaNH2" }, "NH3"));
            R.Add(new PTHH(new List<string> { "NaOH", "C4H8O" }, "C"));
            R.Add(new PTHH(new List<string> { "NaOH", "C4H8O" }, "H2O"));
            R.Add(new PTHH(new List<string> { "NaOH", "C4H8O" }, "Na"));
            R.Add(new PTHH(new List<string> { "Cr", "NaOH" }, "Na"));
            R.Add(new PTHH(new List<string> { "Cr", "NaOH" }, "Cr(OH)2"));
            R.Add(new PTHH(new List<string> { "H2", "Na2O" }, "H2O"));
            R.Add(new PTHH(new List<string> { "H2", "Na2O" }, "Na"));
            R.Add(new PTHH(new List<string> { "CO", "Na2O" }, "Na"));
            R.Add(new PTHH(new List<string> { "CO", "Na2O" }, "CO2"));
            R.Add(new PTHH(new List<string> { "C", "Na2O" }, "Na"));
            R.Add(new PTHH(new List<string> { "C", "Na2O" }, "CO2"));
            R.Add(new PTHH(new List<string> { "Na2O", "NH3" }, "H2O"));
            R.Add(new PTHH(new List<string> { "Na2O", "NH3" }, "N2"));
            R.Add(new PTHH(new List<string> { "Na2O", "NH3" }, "Na"));
            R.Add(new PTHH(new List<string> { "Al", "Na2O" }, "Al2O3"));
            R.Add(new PTHH(new List<string> { "Al", "Na2O" }, "Na"));
            R.Add(new PTHH(new List<string> { "C", "NaOH" }, "H2"));
            R.Add(new PTHH(new List<string> { "C", "NaOH" }, "Na"));
            R.Add(new PTHH(new List<string> { "C", "NaOH" }, "Na2CO3"));
            R.Add(new PTHH(new List<string> { "CaCl2" }, "Ca"));
            R.Add(new PTHH(new List<string> { "CaCl2" }, "Cl2"));
            R.Add(new PTHH(new List<string> { "CaC2", "H2" }, "C2H2"));
            R.Add(new PTHH(new List<string> { "CaC2", "H2" }, "Ca"));
            R.Add(new PTHH(new List<string> { "Ca3P2" }, "Ca"));
            R.Add(new PTHH(new List<string> { "Ca3P2" }, "P2"));
            R.Add(new PTHH(new List<string> { "CaC2" }, "C"));
            R.Add(new PTHH(new List<string> { "CaC2" }, "Ca"));
            R.Add(new PTHH(new List<string> { "CaH2" }, "Ca"));
            R.Add(new PTHH(new List<string> { "CaH2" }, "H2"));
            R.Add(new PTHH(new List<string> { "CaS" }, "Ca"));
            R.Add(new PTHH(new List<string> { "CaS" }, "S"));
            R.Add(new PTHH(new List<string> { "Al", "CaO" }, "Ca"));
            R.Add(new PTHH(new List<string> { "Al", "CaO" }, "Ca(AlO2)2"));
            R.Add(new PTHH(new List<string> { "H2", "CaCN2" }, "C"));
            R.Add(new PTHH(new List<string> { "H2", "CaCN2" }, "Ca"));
            R.Add(new PTHH(new List<string> { "H2", "CaCN2" }, "NH3"));
            R.Add(new PTHH(new List<string> { "CaO", "H2" }, "Ca"));
            R.Add(new PTHH(new List<string> { "CaO", "H2" }, "H2O"));
            R.Add(new PTHH(new List<string> { "CaO", "CO" }, "Ca"));
            R.Add(new PTHH(new List<string> { "CaO", "CO" }, "CO2"));
            R.Add(new PTHH(new List<string> { "C", "CaO" }, "Ca"));
            R.Add(new PTHH(new List<string> { "C", "CaO" }, "CO2"));
            R.Add(new PTHH(new List<string> { "CaO", "NH3" }, "Ca"));
            R.Add(new PTHH(new List<string> { "CaO", "NH3" }, "H2O"));
            R.Add(new PTHH(new List<string> { "CaO", "NH3" }, "N2"));
            R.Add(new PTHH(new List<string> { "BaCl2" }, "Cl2"));
            R.Add(new PTHH(new List<string> { "BaCl2" }, "Ba"));
            R.Add(new PTHH(new List<string> { "Al", "BaO" }, "Ba"));
            R.Add(new PTHH(new List<string> { "Al", "BaO" }, "Ba(AlO2)2"));
            R.Add(new PTHH(new List<string> { "BaS" }, "S"));
            R.Add(new PTHH(new List<string> { "BaS" }, "Ba"));
            R.Add(new PTHH(new List<string> { "BaO", "Si" }, "Ba"));
            R.Add(new PTHH(new List<string> { "BaO", "Si" }, "BaSiO3"));
            R.Add(new PTHH(new List<string> { "BaH2" }, "H2"));
            R.Add(new PTHH(new List<string> { "BaH2" }, "Ba"));
            R.Add(new PTHH(new List<string> { "Zn", "BaSO4" }, "ZnSO4"));
            R.Add(new PTHH(new List<string> { "Zn", "BaSO4" }, "Ba"));
            R.Add(new PTHH(new List<string> { "Fe", "BaSO4" }, "Ba"));
            R.Add(new PTHH(new List<string> { "Fe", "BaSO4" }, "FeSO4"));
            R.Add(new PTHH(new List<string> { "Mg", "BaSO4" }, "Ba"));
            R.Add(new PTHH(new List<string> { "Mg", "BaSO4" }, "MgSO4"));
            R.Add(new PTHH(new List<string> { "BaO", "H2" }, "H2O"));
            R.Add(new PTHH(new List<string> { "BaO", "H2" }, "Ba"));
            R.Add(new PTHH(new List<string> { "BaO", "CO" }, "Ba"));
            R.Add(new PTHH(new List<string> { "BaO", "CO" }, "CO2"));
            R.Add(new PTHH(new List<string> { "BaO", "C" }, "Ba"));
            R.Add(new PTHH(new List<string> { "BaO", "C" }, "CO2"));
            R.Add(new PTHH(new List<string> { "BaO", "NH3" }, "H2O"));
            R.Add(new PTHH(new List<string> { "BaO", "NH3" }, "N2"));
            R.Add(new PTHH(new List<string> { "BaO", "NH3" }, "Ba"));
            R.Add(new PTHH(new List<string> { "MgCl2" }, "Cl2"));
            R.Add(new PTHH(new List<string> { "MgCl2" }, "Mg"));
            R.Add(new PTHH(new List<string> { "K", "MgBr" }, "KBr"));
            R.Add(new PTHH(new List<string> { "K", "MgBr" }, "Mg"));
            R.Add(new PTHH(new List<string> { "C", "MgO" }, "CO"));
            R.Add(new PTHH(new List<string> { "C", "MgO" }, "Mg"));
            R.Add(new PTHH(new List<string> { "CaO", "MgO", "FeSi" }, "Fe"));
            R.Add(new PTHH(new List<string> { "CaO", "MgO", "FeSi" }, "Mg"));
            R.Add(new PTHH(new List<string> { "CaO", "MgO", "FeSi" }, "Ca2SiO4"));
            R.Add(new PTHH(new List<string> { "MgO", "Be" }, "Mg"));
            R.Add(new PTHH(new List<string> { "MgO", "Be" }, "BeO"));
            R.Add(new PTHH(new List<string> { "Mg3N2" }, "Mg"));
            R.Add(new PTHH(new List<string> { "Mg3N2" }, "N2"));
            R.Add(new PTHH(new List<string> { "CaO", "MgO", "SiO" }, "Mg"));
            R.Add(new PTHH(new List<string> { "CaO", "MgO", "SiO" }, "Ca2SiO4"));
            R.Add(new PTHH(new List<string> { "H2", "MgO" }, "H2O"));
            R.Add(new PTHH(new List<string> { "H2", "MgO" }, "Mg"));
            R.Add(new PTHH(new List<string> { "CO", "MgO" }, "Mg"));
            R.Add(new PTHH(new List<string> { "CO", "MgO" }, "CO2"));
            R.Add(new PTHH(new List<string> { "Na", "MgCl2" }, "Mg"));
            R.Add(new PTHH(new List<string> { "Na", "MgCl2" }, "NaCl"));
            R.Add(new PTHH(new List<string> { "C", "MgO" }, "Mg"));
            R.Add(new PTHH(new List<string> { "C", "MgO" }, "CO2"));
            R.Add(new PTHH(new List<string> { "AlCl3", "K" }, "Al"));
            R.Add(new PTHH(new List<string> { "AlCl3", "K" }, "KCl"));
            R.Add(new PTHH(new List<string> { "AlCl3", "Mg" }, "Al"));
            R.Add(new PTHH(new List<string> { "AlCl3", "Mg" }, "MgCl2"));
            R.Add(new PTHH(new List<string> { "AlCl3" }, "Al"));
            R.Add(new PTHH(new List<string> { "AlCl3" }, "Cl2"));
            R.Add(new PTHH(new List<string> { "AlCl3", "Mn" }, "Al"));
            R.Add(new PTHH(new List<string> { "AlCl3", "Mn" }, "MnCl2"));
            R.Add(new PTHH(new List<string> { "Al4C3" }, "Al"));
            R.Add(new PTHH(new List<string> { "Al4C3" }, "C"));
            R.Add(new PTHH(new List<string> { "H2", "Al4C3" }, "Al"));
            R.Add(new PTHH(new List<string> { "H2", "Al4C3" }, "CH4"));
            R.Add(new PTHH(new List<string> { "LiAlH4" }, "Al"));
            R.Add(new PTHH(new List<string> { "LiAlH4" }, "H2"));
            R.Add(new PTHH(new List<string> { "LiAlH4" }, "LiH"));
            R.Add(new PTHH(new List<string> { "Al2(SO4)3", "Mg" }, "Al"));
            R.Add(new PTHH(new List<string> { "Al2(SO4)3", "Mg" }, "MgSO4"));
            R.Add(new PTHH(new List<string> { "Al2O3" }, "Al"));
            R.Add(new PTHH(new List<string> { "Al2O3" }, "O2"));
            R.Add(new PTHH(new List<string> { "Al2(SO4)3", "Cu" }, "Al"));
            R.Add(new PTHH(new List<string> { "Al2(SO4)3", "Cu" }, "CuSO4"));
            R.Add(new PTHH(new List<string> { "Mg", "Al(NO3)3" }, "Al"));
            R.Add(new PTHH(new List<string> { "Mg", "Al(NO3)3" }, "Mg(NO3)2"));
            R.Add(new PTHH(new List<string> { "Al2O3", "H2" }, "Al"));
            R.Add(new PTHH(new List<string> { "Al2O3", "H2" }, "H2O"));
            R.Add(new PTHH(new List<string> { "Al2O3", "CO" }, "Al"));
            R.Add(new PTHH(new List<string> { "Al2O3", "CO" }, "CO2"));
            R.Add(new PTHH(new List<string> { "AlCl3", "Zn" }, "Al"));
            R.Add(new PTHH(new List<string> { "AlCl3", "Zn" }, "ZnCl2"));
            R.Add(new PTHH(new List<string> { "AlCl3", "Fe" }, "Al"));
            R.Add(new PTHH(new List<string> { "AlCl3", "Fe" }, "FeCl2"));
            R.Add(new PTHH(new List<string> { "Cu", "Al(NO3)3" }, "Al"));
            R.Add(new PTHH(new List<string> { "Cu", "Al(NO3)3" }, "Cu(NO3)2"));
            R.Add(new PTHH(new List<string> { "Ag", "Al(NO3)3" }, "AgNO3"));
            R.Add(new PTHH(new List<string> { "Ag", "Al(NO3)3" }, "Al"));
            R.Add(new PTHH(new List<string> { "Al2O3", "C" }, "Al"));
            R.Add(new PTHH(new List<string> { "Al2O3", "C" }, "CO2"));
            R.Add(new PTHH(new List<string> { "Zn", "Al(NO3)3" }, "Al"));
            R.Add(new PTHH(new List<string> { "Zn", "Al(NO3)3" }, "Zn(NO3)2"));
            R.Add(new PTHH(new List<string> { "AgNO3", "Fe" }, "Ag"));
            R.Add(new PTHH(new List<string> { "AgNO3", "Fe" }, "Fe(NO3)3"));
            R.Add(new PTHH(new List<string> { "AgNO3", "Fe" }, "Ag"));
            R.Add(new PTHH(new List<string> { "AgNO3", "Fe" }, "Fe(NO3)2"));
            R.Add(new PTHH(new List<string> { "Cl2", "Fe" }, "FeCl3"));
            R.Add(new PTHH(new List<string> { "Cl2", "Fe" }, "Cl2"));
            R.Add(new PTHH(new List<string> { "Cu(NO3)2", "Fe" }, "Cu"));
            R.Add(new PTHH(new List<string> { "Cu(NO3)2", "Fe" }, "Fe(NO3)2"));
            R.Add(new PTHH(new List<string> { "Fe", "CuSO4" }, "Cu"));
            R.Add(new PTHH(new List<string> { "Fe", "CuSO4" }, "FeSO4"));
            R.Add(new PTHH(new List<string> { "Fe", "Fe(NO3)3" }, "Fe(NO3)2"));
            R.Add(new PTHH(new List<string> { "Fe", "Fe(NO3)3" }, "Fe"));
            R.Add(new PTHH(new List<string> { "Fe", "H2O" }, "FeO"));
            R.Add(new PTHH(new List<string> { "Fe", "H2O" }, "H2"));
            R.Add(new PTHH(new List<string> { "Fe", "H2O" }, "H2"));
            R.Add(new PTHH(new List<string> { "Fe", "H2O" }, "Fe3O4"));
            R.Add(new PTHH(new List<string> { "Fe", "H2SO4" }, "H2"));
            R.Add(new PTHH(new List<string> { "Fe", "H2SO4" }, "FeSO4"));
            R.Add(new PTHH(new List<string> { "Fe", "H2SO4" }, "Fe2(SO4)3"));
            R.Add(new PTHH(new List<string> { "Fe", "H2SO4" }, "H2O"));
            R.Add(new PTHH(new List<string> { "Fe", "H2SO4" }, "SO2"));
            R.Add(new PTHH(new List<string> { "Fe", "HCl" }, "FeCl2"));
            R.Add(new PTHH(new List<string> { "Fe", "HCl" }, "H2"));
            R.Add(new PTHH(new List<string> { "Fe", "HNO3" }, "H2O"));
            R.Add(new PTHH(new List<string> { "Fe", "HNO3" }, "NO2"));
            R.Add(new PTHH(new List<string> { "Fe", "HNO3" }, "Fe(NO3)3"));
            R.Add(new PTHH(new List<string> { "Fe", "O2" }, "Fe3O4"));
            R.Add(new PTHH(new List<string> { " Fe", "S" }, "FeS"));
            R.Add(new PTHH(new List<string> { " Fe", "HCl", "Fe3O4" }, "FeCl2"));
            R.Add(new PTHH(new List<string> { " Fe", "HCl", "Fe3O4" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Fe", "CuCl2" }, "Cu"));
            R.Add(new PTHH(new List<string> { " Fe", "CuCl2" }, "FeCl2"));
            R.Add(new PTHH(new List<string> { " Fe", "HNO3" }, "Fe(NO3)2"));
            R.Add(new PTHH(new List<string> { " Fe", "HNO3" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Fe", "HNO3" }, "NH4NO3"));
            R.Add(new PTHH(new List<string> { " Fe", "H2O2" }, "Fe(OH)3"));
            R.Add(new PTHH(new List<string> { " Fe", "HNO3" }, "Fe(NO3)2"));
            R.Add(new PTHH(new List<string> { " Fe", "HNO3" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Fe", "HNO3" }, "N2"));
            R.Add(new PTHH(new List<string> { " Fe", "Fe2O3" }, "FeO"));
            R.Add(new PTHH(new List<string> { " Fe", "O2" }, "Fe2O3"));
            R.Add(new PTHH(new List<string> { " Fe", "Fe3O4" }, "FeO"));
            R.Add(new PTHH(new List<string> { " Fe", "HNO3" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Fe", "HNO3" }, "NO"));
            R.Add(new PTHH(new List<string> { " Fe", "HNO3" }, "Fe(NO3)3"));
            R.Add(new PTHH(new List<string> { " Fe", "H2O", "O2" }, "Fe(OH)2"));
            R.Add(new PTHH(new List<string> { " Fe", "H3PO4" }, "H2"));
            R.Add(new PTHH(new List<string> { " Fe", "H3PO4" }, "Fe3(PO4)2"));
            R.Add(new PTHH(new List<string> { " Fe", "H3PO4" }, "FeHPO4"));
            R.Add(new PTHH(new List<string> { " Fe", "KNO3", "KOH" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Fe", "KNO3", "KOH" }, "KNO2"));
            R.Add(new PTHH(new List<string> { " Fe", "KNO3", "KOH" }, "K2FeO4"));
            R.Add(new PTHH(new List<string> { " Fe", "H2O", "O2", "CO2" }, "Fe(HCO3)2"));
            R.Add(new PTHH(new List<string> { " Fe", "SO2" }, "FeSO3"));
            R.Add(new PTHH(new List<string> { " Fe", "SO2" }, "FeS2O3"));
            R.Add(new PTHH(new List<string> { " Fe", "O2" }, "FeO"));
            R.Add(new PTHH(new List<string> { " Fe", "NaHSO4" }, "H2"));
            R.Add(new PTHH(new List<string> { " Fe", "NaHSO4" }, "Na2SO4"));
            R.Add(new PTHH(new List<string> { " Fe", "NaHSO4" }, "FeSO4"));
            R.Add(new PTHH(new List<string> { " Fe", "H2O" }, "H2"));
            R.Add(new PTHH(new List<string> { " Fe", "H2O" }, "Fe3O4"));
            R.Add(new PTHH(new List<string> { " Fe", "HCl", "KNO3" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Fe", "HCl", "KNO3" }, "KCl"));
            R.Add(new PTHH(new List<string> { " Fe", "HCl", "KNO3" }, "NO"));
            R.Add(new PTHH(new List<string> { " Fe", "HCl", "KNO3" }, "FeCl3"));
            R.Add(new PTHH(new List<string> { " Fe", "BaSO4" }, "Ba"));
            R.Add(new PTHH(new List<string> { " Fe", "BaSO4" }, "FeSO4"));
            R.Add(new PTHH(new List<string> { " Fe", "HCl", "NaNO3" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Fe", "HCl", "NaNO3" }, "NaCl"));
            R.Add(new PTHH(new List<string> { " Fe", "HCl", "NaNO3" }, "NO"));
            R.Add(new PTHH(new List<string> { " Fe", "HCl", "NaNO3" }, "FeCl3"));
            R.Add(new PTHH(new List<string> { " Fe", "H2SO4" }, "Fe2(SO4)3"));
            R.Add(new PTHH(new List<string> { " Fe", "H2SO4" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Fe", "H2SO4" }, "H2S"));
            R.Add(new PTHH(new List<string> { " Fe", "Fe2(SO4)3" }, "FeSO4"));
            R.Add(new PTHH(new List<string> { " Fe", "KNO3" }, "Fe2O3"));
            R.Add(new PTHH(new List<string> { " Fe", "KNO3" }, "K2O"));
            R.Add(new PTHH(new List<string> { " Fe", "KNO3" }, "N2"));
            R.Add(new PTHH(new List<string> { " Fe", "HNO3" }, "Fe(NO3)2"));
            R.Add(new PTHH(new List<string> { " Fe", "HNO3" }, ""));
            R.Add(new PTHH(new List<string> { " Fe", "HNO3" }, "H2"));
            R.Add(new PTHH(new List<string> { " Fe", "HNO3" }, "H2"));
            R.Add(new PTHH(new List<string> { " Fe", "HNO3" }, "Fe(NO3)3"));
            R.Add(new PTHH(new List<string> { " Fe", "ZnCl2" }, "FeCl2"));
            R.Add(new PTHH(new List<string> { " Fe", "ZnCl2" }, "Zn"));
            R.Add(new PTHH(new List<string> { " AlCl3", "Fe" }, "Al"));
            R.Add(new PTHH(new List<string> { " AlCl3", "Fe" }, "FeCl2"));
            R.Add(new PTHH(new List<string> { " Fe", "H2SO4" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Fe", "H2SO4" }, "SO2"));
            R.Add(new PTHH(new List<string> { " Fe", "H2SO4" }, "FeSO4"));
            R.Add(new PTHH(new List<string> { " Fe", "H2SO4", "NaNO3" }, "Fe2(SO4)3"));
            R.Add(new PTHH(new List<string> { " Fe", "H2SO4", "NaNO3" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Fe", "H2SO4", "NaNO3" }, "Na2SO4"));
            R.Add(new PTHH(new List<string> { " Fe", "H2SO4", "NaNO3" }, "NO"));
            R.Add(new PTHH(new List<string> { " Fe", "HNO3" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Fe", "HNO3" }, "N2O"));
            R.Add(new PTHH(new List<string> { " Fe", "HNO3" }, "Fe(NO3)3"));
            R.Add(new PTHH(new List<string> { " AgNO3", "Cu" }, "Ag"));
            R.Add(new PTHH(new List<string> { " AgNO3", "Cu" }, "Cu(NO3)2"));
            R.Add(new PTHH(new List<string> { " Cl2", "Cu" }, "CuCl2"));
            R.Add(new PTHH(new List<string> { " Cu", "Fe(NO3)3" }, "Cu(NO3)2"));
            R.Add(new PTHH(new List<string> { " Cu", "Fe(NO3)3" }, "Fe(NO3)2"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4" }, "SO2"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4" }, "CuSO4"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4", "O2" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4", "O2" }, "CuSO4"));
            R.Add(new PTHH(new List<string> { " Cu", "HNO3" }, "Cu(NO3)2"));
            R.Add(new PTHH(new List<string> { " Cu", "HNO3" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Cu", "HNO3" }, ""));
            R.Add(new PTHH(new List<string> { " Cu", "HNO3" }, "NO2"));
            R.Add(new PTHH(new List<string> { " Cu", "O2" }, "CuO"));
            R.Add(new PTHH(new List<string> { " Cu", "S" }, "Cu2S"));
            R.Add(new PTHH(new List<string> { " Cu", "S" }, "CuS"));
            R.Add(new PTHH(new List<string> { " Cu", "HCl", "NaNO3" }, "Cu(NO3)2"));
            R.Add(new PTHH(new List<string> { " Cu", "HCl", "NaNO3" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Cu", "HCl", "NaNO3" }, "NaCl"));
            R.Add(new PTHH(new List<string> { " Cu", "HCl", "NaNO3" }, "NO"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4", "Al(NO3)3" }, "Al2(SO4)3"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4", "Al(NO3)3" }, "Cu(NO3)2"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4", "Al(NO3)3" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4", "Al(NO3)3" }, "NO"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4", "Al(NO3)3" }, "CuSO4"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4", "NaNO3" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4", "NaNO3" }, "Na2SO4"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4", "NaNO3" }, "NO"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4", "NaNO3" }, "CuSO4"));
            R.Add(new PTHH(new List<string> { " Cu", "Cu(NO3)2", "HCl" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Cu", "Cu(NO3)2", "HCl" }, "NO"));
            R.Add(new PTHH(new List<string> { " Cu", "Cu(NO3)2", "HCl" }, "CuCl2"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4", "KNO3" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4", "KNO3" }, "NO"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4", "KNO3" }, "K2SO4"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4", "KNO3" }, "CuSO4"));
            R.Add(new PTHH(new List<string> { " Cu", "Fe2(SO4)3" }, "FeSO4"));
            R.Add(new PTHH(new List<string> { " Cu", "Fe2(SO4)3" }, "CuSO4"));
            R.Add(new PTHH(new List<string> { " Br2", "Cu" }, "CuBr2"));
            R.Add(new PTHH(new List<string> { " Cu", "CuO" }, "Cu2O"));
            R.Add(new PTHH(new List<string> { " Cu", "N2O" }, "N2"));
            R.Add(new PTHH(new List<string> { " Cu", "N2O" }, "Cu2O"));
            R.Add(new PTHH(new List<string> { " Cu", "O2" }, "Cu2O"));
            R.Add(new PTHH(new List<string> { " Cu", "SO2" }, "CuO"));
            R.Add(new PTHH(new List<string> { " Cu", "SO2" }, "Cu2S"));
            R.Add(new PTHH(new List<string> { " Cu", "H2O", "O2", "CO2" }, "Cu(OH)2"));
            R.Add(new PTHH(new List<string> { " Cu", "H2O", "O2", "CO2" }, "CuCO3"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4", "NaNO3" }, "Cu(NO3)2"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4", "NaNO3" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4", "NaNO3" }, "Na2SO4"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4", "NaNO3" }, "NO"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4", "Fe(NO3)3" }, "Fe2(SO4)3"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4", "Fe(NO3)3" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4", "Fe(NO3)3" }, "NO"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4", "Fe(NO3)3" }, "CuSO4"));
            R.Add(new PTHH(new List<string> { " Cu", "H2O2", "H2SO4" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Cu", "H2O2", "H2SO4" }, "CuSO4"));
            R.Add(new PTHH(new List<string> { " Cu", "H2S", "O2" }, "CuS"));
            R.Add(new PTHH(new List<string> { " Cu", "H2S", "O2" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Cu", "HCl", "NaNO3" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Cu", "HCl", "NaNO3" }, "NaCl"));
            R.Add(new PTHH(new List<string> { " Cu", "HCl", "NaNO3" }, "NO"));
            R.Add(new PTHH(new List<string> { " Cu", "HCl", "NaNO3" }, "CuCl2"));
            R.Add(new PTHH(new List<string> { " Cu", "HNO3" }, "Cu(NO3)2"));
            R.Add(new PTHH(new List<string> { " Cu", "HNO3" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Cu", "HNO3" }, "NO"));
            R.Add(new PTHH(new List<string> { " Cu", "HCl", "Fe3O4" }, "FeCl2"));
            R.Add(new PTHH(new List<string> { " Cu", "HCl", "Fe3O4" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Cu", "HCl", "Fe3O4" }, ""));
            R.Add(new PTHH(new List<string> { " Cu", "HCl", "Fe3O4" }, "CuCl2"));
            R.Add(new PTHH(new List<string> { " Cu", "H2O", "O2" }, "Cu(OH)2"));
            R.Add(new PTHH(new List<string> { " Cu", "Cu(OH)2" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Cu", "Cu(OH)2" }, "Cu2O"));
            R.Add(new PTHH(new List<string> { " Cu", "HCl", "KNO3" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Cu", "HCl", "KNO3" }, "KCl"));
            R.Add(new PTHH(new List<string> { " Cu", "HCl", "KNO3" }, "NO2"));
            R.Add(new PTHH(new List<string> { " Cu", "HCl", "KNO3" }, "CuCl2"));
            R.Add(new PTHH(new List<string> { " Al2(SO4)3", "Cu" }, "Al"));
            R.Add(new PTHH(new List<string> { " Al2(SO4)3", "Cu" }, "CuSO4"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4", "NH4NO3" }, "(NH4)2SO4"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4", "NH4NO3" }, "Cu(NO3)2"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4", "NH4NO3" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4", "NH4NO3" }, "NO2"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4" }, "CuSO4"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4" }, "SO2"));
            R.Add(new PTHH(new List<string> { " Cu", "FeCl3" }, "FeCl2"));
            R.Add(new PTHH(new List<string> { " Cu", "FeCl3" }, "CuCl2"));
            R.Add(new PTHH(new List<string> { " Cu", "H2O2", "HCl" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Cu", "H2O2", "HCl" }, "CuCl"));
            R.Add(new PTHH(new List<string> { " Cu", "CuCl2" }, "CuCl"));
            R.Add(new PTHH(new List<string> { " Cu", "Ag2SO4" }, "Ag"));
            R.Add(new PTHH(new List<string> { " Cu", "Ag2SO4" }, "CuSO4"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4" }, "H2"));
            R.Add(new PTHH(new List<string> { " Cu", "H2SO4" }, "CuSO4"));
            R.Add(new PTHH(new List<string> { " Cu", "H2O" }, "Cu(OH)2"));
            R.Add(new PTHH(new List<string> { " Cu", "H2O" }, "H2"));
            R.Add(new PTHH(new List<string> { " Cu", "HNO3" }, "Cu(NO3)2"));
            R.Add(new PTHH(new List<string> { " Cu", "HNO3" }, "H2"));
            R.Add(new PTHH(new List<string> { " Cu", "Fe(NO3)2" }, "Cu(NO3)2"));
            R.Add(new PTHH(new List<string> { " Cu", "Fe(NO3)2" }, "Fe"));
            R.Add(new PTHH(new List<string> { " Cu", "Al(NO3)3" }, "Al"));
            R.Add(new PTHH(new List<string> { " Cu", "Al(NO3)3" }, ""));
            R.Add(new PTHH(new List<string> { " Cu", "Al(NO3)3" }, "Cu(NO3)2"));
            R.Add(new PTHH(new List<string> { " Cu", "ZnCl2" }, "Zn"));
            R.Add(new PTHH(new List<string> { " Cu", "ZnCl2" }, "CuCl2"));
            R.Add(new PTHH(new List<string> { " Cu", "H2O" }, "CuO"));
            R.Add(new PTHH(new List<string> { " Cu", "H2O" }, "H2"));
            R.Add(new PTHH(new List<string> { " Cu", "Zn(NO3)2" }, "Cu(NO3)2"));
            R.Add(new PTHH(new List<string> { " Cu", "Zn(NO3)2" }, "Zn"));
            R.Add(new PTHH(new List<string> { " Cr", "HCl" }, "H2"));
            R.Add(new PTHH(new List<string> { " Cr", "HCl" }, "CrCl2"));
            R.Add(new PTHH(new List<string> { " Cr", "HCl", "O2" }, "H2"));
            R.Add(new PTHH(new List<string> { " Cr", "HCl", "O2" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Cr", "HCl", "O2" }, ""));
            R.Add(new PTHH(new List<string> { " Cr", "HCl", "O2" }, "CrCl3"));
            R.Add(new PTHH(new List<string> { " Cr", "NaNO3", "NaOH" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Cr", "NaNO3", "NaOH" }, "NaNO2"));
            R.Add(new PTHH(new List<string> { " Cr", "NaNO3", "NaOH" }, "Na2CrO4"));
            R.Add(new PTHH(new List<string> { " Cr", "O2" }, "Cr2O3"));
            R.Add(new PTHH(new List<string> { " Cr", "O2" }, "CrO"));
            R.Add(new PTHH(new List<string> { " Cr", "HNO3" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Cr", "HNO3" }, "NO"));
            R.Add(new PTHH(new List<string> { " Cr", "HNO3" }, ""));
            R.Add(new PTHH(new List<string> { " Cr", "HNO3" }, "Cr(NO3)3"));
            R.Add(new PTHH(new List<string> { " Cr", "KClO3" }, "KCl"));
            R.Add(new PTHH(new List<string> { " Cr", "KClO3" }, "Cr2O3"));
            R.Add(new PTHH(new List<string> { " Cr", "CrCl3" }, "CrCl2"));
            R.Add(new PTHH(new List<string> { " Cr", "HNO3" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Cr", "HNO3" }, "NO2"));
            R.Add(new PTHH(new List<string> { " Cr", "HNO3" }, "Cr(NO3)3"));
            R.Add(new PTHH(new List<string> { " Cr", "H2SO4" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Cr", "H2SO4" }, ""));
            R.Add(new PTHH(new List<string> { " Cr", "H2SO4" }, "SO2"));
            R.Add(new PTHH(new List<string> { " Cr", "H2SO4" }, "Cr2(SO4)3"));
            R.Add(new PTHH(new List<string> { " Cr", "O2" }, "Cr2O3"));
            R.Add(new PTHH(new List<string> { " Cl2", "Cr" }, "CrCl3"));
            R.Add(new PTHH(new List<string> { " Cr", "HCl" }, "H2"));
            R.Add(new PTHH(new List<string> { " Cr", "HCl" }, "CrCl2"));
            R.Add(new PTHH(new List<string> { " Cr", "NaOH" }, "Na"));
            R.Add(new PTHH(new List<string> { " Cr", "NaOH" }, "Cr(OH)2"));
            R.Add(new PTHH(new List<string> { " Cr", "H2O" }, "H2"));
            R.Add(new PTHH(new List<string> { " Cr", "H2O" }, "Cr(OH)2"));
            R.Add(new PTHH(new List<string> { " Cr", "HCl", "HNO3" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Cr", "HCl", "HNO3" }, ""));
            R.Add(new PTHH(new List<string> { " Cr", "HCl", "HNO3" }, "NO"));
            R.Add(new PTHH(new List<string> { " Cr", "HCl", "HNO3" }, "CrCl3"));
            R.Add(new PTHH(new List<string> { " Cr", "H2SO4" }, "H2"));
            R.Add(new PTHH(new List<string> { " Cr", "H2SO4" }, "CrSO4"));
            R.Add(new PTHH(new List<string> { " Ag", "HNO3" }, "AgNO3"));
            R.Add(new PTHH(new List<string> { " Ag", "HNO3" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Ag", "HNO3" }, "NO2"));
            R.Add(new PTHH(new List<string> { " Ag", "O3" }, "Ag2O"));
            R.Add(new PTHH(new List<string> { " Ag", "O3" }, "O2"));
            R.Add(new PTHH(new List<string> { " Ag", "HNO3" }, "AgNO3"));
            R.Add(new PTHH(new List<string> { " Ag", "HNO3" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Ag", "HNO3" }, "NO"));
            R.Add(new PTHH(new List<string> { " Ag", "H2SO4" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Ag", "H2SO4" }, "SO2"));
            R.Add(new PTHH(new List<string> { " Ag", "H2SO4" }, "Ag2SO4"));
            R.Add(new PTHH(new List<string> { " Ag", "O2", "SO2" }, "Ag2SO4"));
            R.Add(new PTHH(new List<string> { " Ag", "H2S", "O2" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Ag", "H2S", "O2" }, ""));
            R.Add(new PTHH(new List<string> { " Ag", "H2S", "O2" }, "Ag2S"));
            R.Add(new PTHH(new List<string> { " Ag", "HClO3" }, "AgCl"));
            R.Add(new PTHH(new List<string> { " Ag", "HClO3" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Ag", "HClO3" }, "AgClO3"));
            R.Add(new PTHH(new List<string> { " Ag", "HCl" }, "AgCl"));
            R.Add(new PTHH(new List<string> { " Ag", "HCl" }, "H2"));
            R.Add(new PTHH(new List<string> { " Ag", "H2SO4" }, "H2"));
            R.Add(new PTHH(new List<string> { " Ag", "H2SO4" }, "Ag2SO4"));
            R.Add(new PTHH(new List<string> { " Ag", "H2O" }, "AgOH"));
            R.Add(new PTHH(new List<string> { " Ag", "H2O" }, ""));
            R.Add(new PTHH(new List<string> { " Ag", "H2O" }, "H2"));
            R.Add(new PTHH(new List<string> { " Ag", "Al(NO3)3" }, "AgNO3"));
            R.Add(new PTHH(new List<string> { " Ag", "Al(NO3)3" }, "Al"));
            R.Add(new PTHH(new List<string> { " Ag", "Zn(NO3)2" }, "AgNO3"));
            R.Add(new PTHH(new List<string> { " Ag", "Zn(NO3)2" }, "Zn"));
            R.Add(new PTHH(new List<string> { " Ag", "Fe(NO3)2" }, "AgNO3"));
            R.Add(new PTHH(new List<string> { " Ag", "Fe(NO3)2" }, "Fe"));
            R.Add(new PTHH(new List<string> { " Ag", "H2O" }, "Ag2O"));
            R.Add(new PTHH(new List<string> { " Ag", "H2O" }, "H2"));
            R.Add(new PTHH(new List<string> { " Ag", "Fe(NO3)3" }, "AgNO3"));
            R.Add(new PTHH(new List<string> { " Ag", "Fe(NO3)3" }, "Fe(NO3)2"));
            R.Add(new PTHH(new List<string> { " Ag", "Cu(NO3)2" }, "AgNO3"));
            R.Add(new PTHH(new List<string> { " Ag", "Cu(NO3)2" }, "Cu"));
            R.Add(new PTHH(new List<string> { " Br2", "H2" }, "HBr"));
            R.Add(new PTHH(new List<string> { " Cl2", "H2" }, "HCl"));
            R.Add(new PTHH(new List<string> { " H2", "CO2" }, "C"));
            R.Add(new PTHH(new List<string> { " H2", "CO2" }, "H2O"));
            R.Add(new PTHH(new List<string> { " CuO", "H2" }, "Cu"));
            R.Add(new PTHH(new List<string> { " CuO", "H2" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Fe2O3", "H2" }, "Fe"));
            R.Add(new PTHH(new List<string> { " Fe2O3", "H2" }, "H2O"));
            R.Add(new PTHH(new List<string> { " FeO", "H2" }, "Fe"));
            R.Add(new PTHH(new List<string> { " FeO", "H2" }, "H2O"));
            R.Add(new PTHH(new List<string> { " H2", "N2" }, "NH3"));
            R.Add(new PTHH(new List<string> { " H2", "O2" }, "H2O"));
            R.Add(new PTHH(new List<string> { " H2", "Fe3O4" }, "Fe"));
            R.Add(new PTHH(new List<string> { " H2", "Fe3O4" }, ""));
            R.Add(new PTHH(new List<string> { " H2", "Fe3O4" }, "H2O"));
            R.Add(new PTHH(new List<string> { " H2", "N2O" }, "H2O"));
            R.Add(new PTHH(new List<string> { " H2", "N2O" }, "N2"));
            R.Add(new PTHH(new List<string> { " H2", "ZnO" }, "H2O"));
            R.Add(new PTHH(new List<string> { " H2", "ZnO" }, "Zn"));
            R.Add(new PTHH(new List<string> { " CO", "H2" }, "CH4"));
            R.Add(new PTHH(new List<string> { " CO", "H2" }, "H2O"));
            R.Add(new PTHH(new List<string> { " Ag2O", "H2" }, "Ag"));
            R.Add(new PTHH(new List<string> { " Ag2O", "H2" }, "H2O"));
            R.Add(new PTHH(new List<string> { " H2", "CO2" }, "CH4"));
            R.Add(new PTHH(new List<string> { " H2", "CO2" }, "H2O"));
            R.Add(new PTHH(new List<string> { " FeCl2", "H2" }, "Fe"));
            R.Add(new PTHH(new List<string> { " FeCl2", "H2" }, "HCl"));
            R.Add(new PTHH(new List<string> { " H2", "K2Cr2O7" }, "H2O"));
            R.Add(new PTHH(new List<string> { " H2", "K2Cr2O7" }, "KOH"));
            R.Add(new PTHH(new List<string> { " H2", "K2Cr2O7" }, "Cr2O3"));
            R.Add(new PTHH(new List<string> { " H2", "K2SO4" }, "H2O"));
            R.Add(new PTHH(new List<string> { " H2", "K2SO4" }, "K2S"));
            R.Add(new PTHH(new List<string> { " H2", "Na2SO4" }, "H2O"));
            R.Add(new PTHH(new List<string> { " H2", "Na2SO4" }, "Na2S"));
            R.Add(new PTHH(new List<string> { " H2", "Cu2O" }, "Cu"));
            R.Add(new PTHH(new List<string> { " H2", "Cu2O" }, "H2O"));
            R.Add(new PTHH(new List<string> { " H2", "Ag2SO4" }, "Ag"));
            R.Add(new PTHH(new List<string> { " H2", "Ag2SO4" }, "H2SO4"));
        }
    }

}
